### PR TITLE
Fix weird image output

### PR DESCRIPTION
**Pull request by dcchut**
@eadf pointed out in #13 that some of the example images look weird, e.g. the left-side of the Sierpinski triangle example is completely misaligned:

image

The cause of this is that we store a lot of things (position, most importantly) as an `i32`.  Whenever we want to move a turtle we end up doing:
```rust
fn forward(&mut self, distance: i32) {
    let dx = self.heading.cos() * distance as f32;
    let dy = self.heading.sin() * distance as f32;

    if self.pen_down {
        self.turtle.delta_move(dx as i32, dy as i32);
    }
}
```
i.e. `dx` and `dy` are converted back to an `i32`.  Repeating this enough time leads to the above weirdness.  A fix is to intead store everything as a float (I picked `f64` at random: I suspect there's no appreciable difference to using `f32`), only truncating at the end when it comes time to rendering.  

With this change, the example looks much cleaner:

image

This is a breaking change - I've tried to keep the changes minimal (i.e. affecting the turtles themselves rather than the builders or renderers - you can see that none of the examples below have had to change).

### CODE REVIEW

**Comment by eadf** [comment]
I just discovered that round() on the floats fixes this specific Sierpinski triangle problem.
But a total f64 conversion probably fixes this and other potential problems as well.  

```
   fn forward(&mut self, distance: i32) {
        let dx = self.heading.cos() * distance as f32;
        let dy = self.heading.sin() * distance as f32;

        if self.pen_down {
            self.turtle.delta_move(dx.round() as i32, dy.round() as i32);
        }
    }
```

Try to use `round()` when converting from `f64` to the final `i32`, I suspect that will fix the grid pattern sometimes seen on dense dragon curve images.

Edit: I'd rather take f64 from the data-renderer than i32. It will be converted to f64 later anyways.
But that's only from my perspective. If you like to keep the type symmetry between the data-renderer and image-renderer it is completely up to you.

**Comment by eadf** [comment]
While discussing breaking changes and an upcoming 0.7 release...
May I suggest adding an Error to the public API?

```
use thiserror::Error;

#[derive(Error, Debug)]
// clippy will complain about a name like LSystemError :/
pub enum LSystemError {
    #[error("Invalid data")]
    InvalidData(String),

    #[error("Unknown error")]
    InternalError(String),

    ...
}

...
// all of the builder methods, that can fail, returns Result<&mut Self, LSystemError>
pub fn rule<'a, S: Into<&'a str>>(&mut self, rule: S) -> Result<&mut Self, LSystemError> {
....
// render() returns Result<Self::Output, LSystemError>
fn render(mut self, system: &LSystem, _options: &DataRendererOptions) -> Result<Self::Output, LSystemError> {
....
```

It does not have to be implemented in a first iteration,(i.e. keep panic() and expect() as is for now)
A change like this just makes it easier to add actual error handling in the future.

The examples would then look like this:
```
fn main() -> Result<(), LSystemError>{
    let mut builder = TurtleLSystemBuilder::new();

    builder
        .token("F", TurtleAction::Forward(30))?
        .token("+", TurtleAction::Rotate(90))?
        .token("-", TurtleAction::Rotate(-90))?
        .axiom("F")?
        .rule("F => F + F - F - F + F")?;

    let (mut system, renderer) = builder.finish()?;
    system.step_by(7)?;

    let options = ImageRendererOptionsBuilder::new()
        .padding(10)
        .thickness(4.0)
        .fill_color(Rgb([255u8, 255u8, 255u8]))
        .line_color(Rgb([0u8, 0u8, 100u8]))
        .build()?;

    renderer
        .render(&system, &options)?
        .save("koch_curve.png")?;
}
```

**Comment by dcchut** [comment]
> While discussing breaking changes and an upcoming 0.7 release...
> May I suggest adding an Error to the public API?

That's a reasonable suggestion - I'll look into making another PR for proper error handling.

**Review by eadf — APPROVED** [review]
I think a few nanoseconds can be saved if the result of `thickness*perpendicular_angle.cos()` and `thickness*perpendicular_angle.sin()` is reused instead of re-calculated.

I see that data_renderer is using f64, thanks.

I would have `#[inline]`:ed a the `_r()` function. 

Looking good 

Edit: Have you noticed the vast difference in execution time with and without --release?
dragon curve example with --release: Duration 311.067666ms
dragon curve example with --release + lto: Duration 279.6845ms
dragon curve example without --release: 14.859186458s
Maybe put a comment about that in the Readme

**Pull request merged**
